# Generated by Django 2.1.7 on 2019-05-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arrangements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='attendances',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('arrive_at', models.CharField(max_length=255)),
                ('leave_at', models.CharField(max_length=255)),
                ('is_overtime', models.SmallIntegerField(max_length=4)),
                ('reason', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('director_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=11)),
                ('birthday', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('arrange_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myAPP.arrangements')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myAPP.departments')),
            ],
        ),
        migrations.CreateModel(
            name='empyt',
            fields=[
                ('test', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(max_length=4)),
                ('status', models.SmallIntegerField(max_length=4)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.employees')),
            ],
        ),
        migrations.CreateModel(
            name='managers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='overtimes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='temp_arrangements',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.employees')),
            ],
        ),
    ]
