# Generated by Django 2.1.7 on 2019-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='name',
            field=models.CharField(default='user', max_length=11),
        ),
    ]
