# Generated by Django 2.1.7 on 2019-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0002_attendances_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangements',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arrangements',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
