# Generated by Django 2.1.7 on 2019-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0003_auto_20190607_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrangements',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='arrangements',
            name='period',
        ),
        migrations.RemoveField(
            model_name='arrangements',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='arrangements',
            name='start_time',
        ),
        migrations.AddField(
            model_name='arrangements',
            name='end_time_am',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='end_time_pm',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='start_time_am',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='arrangements',
            name='start_time_pm',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
