# Generated by Django 2.1.7 on 2019-06-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0004_auto_20190607_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangements',
            name='day',
            field=models.CharField(default='-', max_length=255),
        ),
    ]
