# Generated by Django 2.1.7 on 2019-06-08 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0005_arrangements_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimes',
            name='date',
        ),
        migrations.AddField(
            model_name='overtimes',
            name='employee_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myAPP.employees'),
        ),
        migrations.AddField(
            model_name='overtimes',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='overtimes',
            name='status',
            field=models.SmallIntegerField(default=0, max_length=4),
        ),
    ]
