# Generated by Django 2.1.7 on 2019-06-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0007_auto_20190608_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='birthday',
            field=models.CharField(default='', max_length=255),
        ),
    ]
