# Generated by Django 2.1.7 on 2019-06-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0008_managers_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
