# Generated by Django 2.1.7 on 2019-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0010_employees_issupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='notice',
            field=models.CharField(default='', max_length=255),
        ),
    ]
