# Generated by Django 2.1.7 on 2019-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0011_attendances_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendances',
            name='reason',
        ),
        migrations.AddField(
            model_name='attendances',
            name='department_id',
            field=models.IntegerField(default=1),
        ),
    ]
