# Generated by Django 2.1.7 on 2019-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0012_auto_20190615_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendances',
            name='overtime_id',
            field=models.IntegerField(default=0),
        ),
    ]
