# Generated by Django 2.1.7 on 2019-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0013_attendances_overtime_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='over_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255)),
                ('end_time', models.CharField(max_length=255)),
            ],
        ),
    ]
